import Head from "next/head";
import styles from "../styles/Home.module.css";

import Hero from "../components/hero/Hero";
import Galeria from "../components/Galeria/Galeria";
import Footer from "../components/footer/Footer";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Folcademy Next app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Hero />
        <Galeria />
      </main>
      <Footer />
    </div>
  );
}
