import Head from "next/head";
import styles from "../styles/Home.module.css";
import NavBar from "../components/navbar/NavBar";
import Footer from "../components/footer/Footer";
import PopularMovies from "../components/popular-movies/PopularMovies";
import TerrorMovies from "../components/terror-movies/TerrorMovies";
import DramaMovies from "../components/drama-movies/DramaMovies";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Folcademy Next app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />
      <div className={styles.section__container}>
        <PopularMovies />
        <TerrorMovies />
        <DramaMovies />
      </div>
      <Footer />
    </div>
  );
}
