import Head from "next/head";
import styles from "../styles/Home.module.css";

import Hero from "../components/hero/Hero";
import InfoCards from "../components/InfoCards/InfoCards";
import Gallery from "../components/Gallery/Gallery";
import Footer from "../components/footer/Footer";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Folcademy Next app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Hero />
        <InfoCards />
        <Gallery />
      </main>

      <Footer />
    </div>
  );
}
